name: tie_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  domain:
    path: packages/domain
  data:
    path: packages/data

  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed: ^2.4.5
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
  test: ^1.24.1
  bloc_test: ^9.1.3

flutter:
  uses-material-design: true
