name: ui
description: TIE UI.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^5.0.0+1
